server:
  port: 8082

spring:
  application:
    name: app

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://highload-db:5432/highload
    username: postgres
    password: password

app:
  default-page-size: 50
  max-page-size: 50

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
