server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: user-swagger
              uri: lb://user-accounter
              predicates:
                - Path=/user/v3/api-docs
              filters:
                - StripPrefix=1

            - id: user-accounter-route
              uri: lb://user-accounter
              predicates:
                - Path=/user/**

            - id: app-swagger
              uri: lb://app
              predicates:
                - Path=/app/v3/api-docs
              filters:
                - StripPrefix=1

            - id: app-route
              uri: lb://app
              predicates:
                - Path=/app/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: App Service
        url: /app/v3/api-docs
      - name: User Accounter
        url: /user/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
