server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: app-route
          uri: http://localhost:8082
          predicates:
            - Path=/**
          filters:
            - SetPath=/{path}


#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui/index.html
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - url: /v3/api-docs
#        name: API Gateway Service
#      - url: /api/v1/user/v3/api-docs
#        name: User Service
#      - url: /api/v1/event/v3/api-docs
#        name: Event Service
#      - url: /api/v1/group-event/v3/api-docs
#        name: Group Event Service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true