server:
  forward-headers-strategy: framework
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: user-accounter-swagger
              uri: lb://user-accounter
              predicates:
                - Path=/user-accounter/v3/api-docs
              filters:
                - RewritePath=/user-accounter/(?<segment>.*), /$\{segment}

            - id: dish-service-swagger
              uri: lb://dish-service
              predicates:
                - Path=/dish-service/v3/api-docs
              filters:
                - RewritePath=/dish-service/(?<segment>.*), /$\{segment}

            - id: menu-service-swagger
              uri: lb://menu-service
              predicates:
                - Path=/menu-service/v3/api-docs
              filters:
                - RewritePath=/menu-service/(?<segment>.*), /$\{segment}

            - id: user-accounter
              uri: lb://user-accounter
              predicates:
                - Path=/user/**,/register,/login
              filters:
                - name: CircuitBreaker
                  args:
                    name: myCircuitBreaker
                    fallbackUri: forward:/service-unavailable

            - id: dish-service
              uri: lb://dish-service
              predicates:
                - Path=/dish/**,/item/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: myCircuitBreaker
                    fallbackUri: forward:/service-unavailable

            - id: menu-service
              uri: lb://menu-service
              predicates:
                - Path=/menu/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: Circuit Breaker
                    fallbackUri: forward:/service-unavailable

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: Dish Service
        url: /dish-service/v3/api-docs
      - name: Menu Service
        url: /menu-service/v3/api-docs
      - name: User Accounter
        url: /user-accounter/v3/api-docs
      - name: Application
        url: /v3/api-docs/aggregated

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
