server:
  port: 8082

spring:
  application:
    name: highload-app

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://highload-db:5432/highload
    username: postgres
    password: password

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: false

app:
  default-page-size: 50
  max-page-size: 50

# Eureka Configuration
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
