server:
  port: 8083

spring:
  application:
    name: menu-service

  r2dbc:
    url: r2dbc:postgresql://menu-service-db:5432/highload
    username: postgres
    password: password

  liquibase:
    url: jdbc:postgresql://menu-service-db:5432/highload
    user: postgres
    password: password
    enabled:
      true
    change-log:
      changelog/db.changelog-master.xml

app:
  default-page-size: 50
  max-page-size: 50

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

resilience4j:
  circuitbreaker:
    instances:
      dish-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        slowCallDurationThreshold: 2000
        slowCallRateThreshold: 50
      user-accounter:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        slowCallDurationThreshold: 2000
        slowCallRateThreshold: 50
  timelimiter:
    instances:
      product-service:
        timeoutDuration: 10s
      user-service:
        timeoutDuration: 10s

feign:
  circuitbreaker:
    enabled: true