server:
  port: 8083

spring:
  application:
    name: menu-service

  r2dbc:
    url: r2dbc:postgresql://menu-service-db:5432/highload
    username: postgres
    password: password

app:
  default-page-size: 50
  max-page-size: 50

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
