server:
  port: 8081

spring:
  application:
    name: user-accounter

  r2dbc:
    url: r2dbc:postgresql://user-accounter-db:5432/highload
    username: postgres
    password: password

  liquibase:
    url: jdbc:postgresql://user-accounter-db:5432/highload
    user: postgres
    password: password
    enabled:
      true
    change-log:
      changelog/db.changelog-master.xml

eureka:
  instance:
    hostname: user-accounter
    prefer-ip-address: false
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
