server:
  port: 8081

spring:
  application:
    name: user-accounter

  datasource:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://highload-db:5432/highload
    username: postgres
    password: password

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
